server:
  port: 8081
spring:
  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.131:2881/test?characterEncoding=UTF-8
    username: root
#    password: ******
#spring.jpa.hibernate.ddl-auto=update
jackson:
  serialization:
    indent_output: true


logging:
  level:
    com.zhiend.oceanbase: info
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  type-aliases-package: com.zhiend.oceanbase.entity
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


knife4j:
  enable: true
  openapi:
    title: 管理接口文档
    description: "管理接口文档"
    email: sse_d@qq.com
    concat: zhiend
    url: http://localhost:8081/doc.html
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.zhiend.oceanbase.controller